# Generated by Django 3.1.3 on 2021-03-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin',
            new_name='administrateur',
        ),
    ]
