# Generated by Django 3.1.7 on 2021-03-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0003_remove_location_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='email',
        ),
    ]
