# Generated by Django 3.1.7 on 2021-03-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0004_remove_administrateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='email',
            field=models.EmailField(default=0, max_length=254, null=0),
            preserve_default=False,
        ),
    ]
