# Generated by Django 3.1.7 on 2021-03-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0006_auto_20210325_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
