# Generated by Django 3.1.7 on 2021-03-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0007_auto_20210325_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
