# Generated by Django 3.1.7 on 2021-03-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0009_image_texte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='intitule',
            new_name='description',
        ),
    ]
