# Generated by Django 3.1.7 on 2021-03-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0010_auto_20210331_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='confirmer',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
