# Generated by Django 3.1.7 on 2021-03-31 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monapi', '0014_location_confirmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='confirmer',
        ),
    ]
